### ISSUE TITLE
Document mirroring to ECR public registry

### ISSUE THREAD

**Issue by guanzo** [seatgeek/docker-mirror#70]
Wasn't sure if I could upload to a public registry since the docs only mention private registries, but got it working like so

Login:
```bash
aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
```

config.yaml
```yaml
target:
  registry: public.ecr.aws

  # Default or custom alias
  prefix: "j6h4p2z2/"

repositories:
  - name: alpine
    match_tag:
    - "3.10"
```
