### ISSUE TITLE
Add feature to mirror Quay.io (http://quay.io/) and GCR images to Public ECR repos

### ISSUE THREAD

**Issue by alolita** [seatgeek/docker-mirror#77]
I’d like to have the ability to use docker-mirror to support mirroring of non-Docker repo images from Quay container registry and Google Container Registry (GCR) to be published in public ECR repos. 

An example YAML file would look as follows:

```
target:
  registry: ACCOUNT_ID.dkr.REGION.amazonaws.com
  prefix: "hub/"
repositories:
  - name: quay.io/opentelemetry/opentelemetry-operator
      - "v*"

  - name: gcr.io/kubebuilder/kube-rbac-proxy
      - max_tags: 10
```

We are working on an enhancement which we plan to contribute to the project. 

cc: @saber-W 

There are a couple of related issues open which will hopefully also get addressed by our upcoming PR. 

Related Issues:
https://github.com/seatgeek/docker-mirror/issues/75
https://github.com/seatgeek/docker-mirror/issues/70
